# Generated by Django 3.0.4 on 2020-09-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20200923_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
