# Generated by Django 3.0.4 on 2020-09-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20200923_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='day',
            new_name='doneday',
        ),
    ]
